routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\StaticPageController;

// Begin: route namespace charity
// route login charity and admin

// AUTH ROUTES
Route::namespace('Auth')->middleware(['guest', 'lang'])->group(function(){
    // login
    Route::get('login/{role?}' , 'LoginController@login')->name('admin.login');
    Route::post('login/auth' , 'LoginController@loginAuth')->name('login.auth');
    
    Route::get('authorized'      , 'AuthorizedConrtoller@authorized')->name('authorized');
    Route::get('return-authorized'      , 'AuthorizedConrtoller@returnAuthorized')->name('return.authorized');

    // Forgot password routes
    Route::get('forgot-password' , 'PasswordController@getPasswordForm')->name('forgot-password');
    Route::post('send-link', 'PasswordController@sendResetPasswordLink')->name('send-reset-password-link');
    Route::get('reset-password/{email}/{role}', 'PasswordController@resetPassword')->name('reset-password');
    Route::post('store-new-password', 'PasswordController@storeNewPassword')->name('store-new-password');
    
});

Route::namespace('Auth')->group(function(){
    // route logout
    Route::get('logout' , 'LoginController@logout')->name('admin.logout')->middleware('lang');
    // route take token firebase
    Route::post('save-token' , 'UserController@saveToken')->name('save-token');

});

// Change language
Route::get('lang/{lang}', 'Web\MainController@lang')->name('lang');

// Get charity category services
Route::post('get-category-services', 'Web\MainController@getCategoryServices')->name('get-category-services')->middleware('lang');
Route::post('get-service-features', 'Web\MainController@getServiceFeatures')->name('get-service-features')->middleware('lang');


//------------------------------------------------------------------------------------------------------------------------------------------------




// BEGIN: CHARITY ROUTES
Route::middleware(['role:charity|charity_employee', 'auth:charity' , 'lang'])->prefix('charity')->name('charity.')->namespace('Charity')->group(function() {

    // route index dashbaord
    Route::get('/dashboard' , 'DashboardController@index')->name('dashboard');
    // route profile
    Route::get('/dashboard/profile' , 'ProfileController@index')->name('dashboard.profile');
    Route::get('/dashboard/profile/edit' , 'ProfileController@edit')->name('dashboard.profile.edit');
    Route::put('/dashboard/profile/update' , 'ProfileController@update')->name('dashboard.profile.update');
    // route charities
    Route::resource('charities' , 'CharityController');      
    Route::post('send/request/edit/charity' , 'ProfileController@sendRequestEdit')->name('send.request.edit.charity');
    
    // Employee edit profile request
    Route::get('profile-edit', 'ProfileController@editEmployeeProfile')->name('emp-profile.edit');
    Route::put('profile-update', 'ProfileController@UpdateEmployeeProfile')->name('emp-profile.update');

    // change currency             
    Route::get('exchange/{currency_id}', [App\Http\Controllers\Admin\MainController::class, 'exchangeCurrency'])->name('main.exchange_currency');
    // route contact charity
    Route::get('/contract' , 'ProfileController@contract')->name('contract');
    Route::post('/signature' , 'ProfileController@signature')->name('signature');
    
    Route::middleware(['contract' , 'status'])->group(function() {

        // route projects
        Route::resource('projects' , 'ProjectController'); 
        Route::post('send/request/edit' , 'ProjectController@sendRequestEdit')->name('send.request.edit');              
        Route::get('delete/image/project' , 'ProjectController@deleteImage')->name('delete.image.project');              
        // route phases
        Route::resource('phases' , 'PhasesController');    
        Route::get('get/start/date/project' , 'PhasesController@getStartDateProject')->name('get.start.date.project');              
        // route report
        Route::resource('reports' , 'ReportController');              
        Route::get('delete/image' , 'ReportController@deleteImage')->name('delete.image');              
        Route::get('phase/{id}/{type}' , 'ReportController@create')->name('phase');  
        // sponsers
        Route::resource('sponsers' , 'SponserController');              
        // route cities of country
        Route::get('cities' , 'CityController@cityOfCountry')->name('cities');
          
        // exchange
        Route::get('order/exchange' , 'ExchangeController@orderExchange')->name('order.exchange');              
        Route::get('bond/exchange' , 'ExchangeController@BondExchange')->name('bond.exchange');              
        Route::post('accept/bond' , 'ExchangeController@acceptBond')->name('accept.bond');  
        
        // route employee
        Route::resource('employees' , 'EmployeeController');

        // route Job categories
        Route::resource('job-categories' , 'JobCategoryController');
        // jop of jop category
        Route::get('jop/jopCategory' , 'JobCategoryController@jopOfJopCategory')->name('jop.jopCategory');

        // route Jobs
        Route::resource('jobs' , 'JobController');

        // Degrees route
        Route::resource('degrees' , 'DegreeController');

        // Nationalities route
        Route::resource('nationalities' , 'NationalityController');
        
     });


      
}); // END: CHARITY ROUTES



//--------------------------------------------------------------------------------------------------------------------------------------------------




// BEGIN: ADMIN ROUTES
Route::middleware(['role:admin|employee' , 'auth:web', 'lang'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

    // Admin home
    Route::get('/' , 'HomeController@index')->name('home');

    //Main Controller
    Route::post('get-diff-days', [App\Http\Controllers\Admin\MainController::class, 'diffDays'])->name('get-diff-days');
    Route::post('change-status', [App\Http\Controllers\Admin\MainController::class, 'changeStatus'])->name('main.change-status');
    Route::post('delete-image', [App\Http\Controllers\Admin\MainController::class, 'deleteImage'])->name('main.delete-image');
    Route::get('exchange/{currency_id}', [App\Http\Controllers\Admin\MainController::class, 'exchangeCurrency'])->name('main.exchange_currency');

    // Profile (Admin + Employee)
    Route::get('profile', [App\Http\Controllers\Admin\MainController::class, 'editProfile'])->name('profile.edit');
    Route::put('profile/{id}', [App\Http\Controllers\Admin\MainController::class, 'updateProfile'])->name('profile.update');


    // Static Pages
    Route::get('static-pages', [StaticPageController::class, 'getStaticPagesByNation'])->name('static-pages.index');
    Route::get('static-pages/{id}/edit', [StaticPageController::class, 'edit'])->name('static-pages.edit');
    Route::patch('static-pages/{id}', [StaticPageController::class, 'update'])->name('static-pages.update');

    // Slider
    Route::resource('sliders', SliderController::class)->except(['index', 'show']);
    Route::get('sliders', [App\Http\Controllers\Admin\SliderController::class, 'index'])->name('sliders.index');

    // Charities
    Route::get('charities-status/{status}', [App\Http\Controllers\Admin\CharityController::class, 'getCharityWithStatus'])->name('charities.get-with-status');
    Route::get('export-all-charities/{status}', [App\Http\Controllers\Admin\CharityController::class, 'exportAll'])->name('export-all-charities');
    Route::get('export-charity/{id}', [App\Http\Controllers\Admin\CharityController::class, 'exportCharity'])->name('export-charity');

    
    // Projects Sponsers
    Route::get('sponsers/{project_id}', [App\Http\Controllers\Admin\SponserController::class, 'create'])->name('sponsers.create');
    Route::post('sponsers', [App\Http\Controllers\Admin\SponserController::class, 'store'])->name('sponsers.store');
    Route::put('sponsers/{id}', [App\Http\Controllers\Admin\SponserController::class, 'update'])->name('sponsers.update');
    Route::delete('sponsers/{id}', [App\Http\Controllers\Admin\SponserController::class, 'destroy'])->name('sponsers.destroy');

    // Project Phases
    Route::get('phases/{project_id}', [App\Http\Controllers\Admin\PhaseController::class, 'create'])->name('phases.create');
    Route::get('phases/{id}/show', [App\Http\Controllers\Admin\PhaseController::class, 'show'])->name('phases.show');
    Route::post('phases', [App\Http\Controllers\Admin\PhaseController::class, 'store'])->name('phases.store');
    Route::get('phases/{id}/edit', [App\Http\Controllers\Admin\PhaseController::class, 'edit'])->name('phases.edit');
    Route::put('phases/{id}/update', [App\Http\Controllers\Admin\PhaseController::class, 'update'])->name('phases.update');
    Route::delete('phases/{id}/delete', [App\Http\Controllers\Admin\PhaseController::class, 'destroy'])->name('phases.destroy');

    // Resources contrllers
    // contacts
    Route::resource('contacts', ContactController::class)->only(['index', 'destroy']);

    // projects
    Route::get('projects-status/{status}', [App\Http\Controllers\Admin\ProjectController::class, 'getProjectWithStatus'])->name('projects.get-project-with-status');
    Route::post('projects-edit-request', [App\Http\Controllers\Admin\MainController::class, 'changeStatus'])->name('projects-edit-request');
    Route::post('projects/delete-image', [App\Http\Controllers\Admin\ProjectController::class, 'deleteImage'])->name('projects.delete-image');
    Route::get('projects/restore/{id}', [App\Http\Controllers\Admin\ProjectController::class, 'restore'])->name('projects.restore');
    Route::get('export-all-projects/{status}', [App\Http\Controllers\Admin\ProjectController::class, 'exportAll'])->name('export-all-projects');
    Route::get('export-project/{id}', [App\Http\Controllers\Admin\ProjectController::class, 'exportProject'])->name('export-project');

app/Http/Controllers/Charity/CityController.php
<?php

namespace App\Http\Controllers\Charity;

use App\Http\Controllers\Controller;
use App\Repositories\CityRepositoryInterface;
use Illuminate\Http\Request;

class CityController extends Controller
{
    
    public $cityrepository;
   
    public function __construct(CityRepositoryInterface $cityrepository)
    {

        $this->cityrepository    = $cityrepository;
        
    } // end of construct
    
    public function cityOfCountry(Request $request)
    {

        $nation_id = getNationId();

        $cities = $this->cityrepository->getWhere([['nation_id', $nation_id], ['parent_id', $request->id]]);

        return view('charities.projects.cities' , compact('cities'))->render();

    } // end of index    

}

app/Http/Controllers/Charity/DashboardController.php
<?php

namespace App\Http\Controllers\Charity;

use App\Http\Controllers\Controller;
use App\Repositories\PhaseRepositoryInterface;
use App\Repositories\ProjectRepositoryInterface;
use App\Repositories\ProjectUserRepositoryInterface;
use App\Repositories\SponserRepositoryInterface;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public $projectrepository;
    public $sponserrepository;
    public $phasesrepository;
    public $projectuserrepository;

    public function __construct(ProjectRepositoryInterface $projectrepository ,
                                SponserRepositoryInterface $sponserrepository,
                                PhaseRepositoryInterface $phasesrepository,
                                ProjectUserRepositoryInterface $projectuserrepository
                                )
    {
     
        $this->projectrepository     = $projectrepository;
        $this->sponserrepository     = $sponserrepository;
        $this->phasesrepository      = $phasesrepository;
        $this->projectuserrepository = $projectuserrepository;

        $this->middleware(function ($request, $next) {

            if(auth()->user()->hasRole('charity_employee')){

                $this->user = auth()->user()->charity;
            }
            else{
                
                $this->user = auth()->user();
            }

            return $next($request);
        });
        
    }

    public function index()
    {
        // if(auth()->user()->hasRole('charity_employee')){
        //     $user = auth()->user()->charity;
        // }
        // else{

        //     $user = auth()->user();
        // }

        // dd(checkPermissions(['list_projects_'.$user->id]) || checkPermissions(['create_projects_'.$user->id]) || 
        // checkPermissions(['edit_projects_'.$user->id]) || checkPermissions(['show_projects_'.$user->id]) || 
        // checkPermissions(['delete_projects_'.$user->id]) ||
        // checkPermissions(['list_phases_'.$user->id]) || checkPermissions(['create_phases_'.$user->id]) || 
        // checkPermissions(['edit_phases_'.$user->id]) || checkPermissions(['show_phases_'.$user->id]) || 
        // checkPermissions(['delete_phases_'.$user->id]));

        $ids      = $this->user->projects()->pluck('id');
        $sponsers = $this->sponserrepository->count($ids);
        $phases   = $this->phasesrepository->count($ids);
        $cost_donate = $this->projectuserrepository->costAllProject($ids);

        // get status projects
        // $project_waiting  = $this->projectrepository->waiting();
        // $project_approved = $this->projectrepository->approved();
        // $project_rejected = $this->projectrepository->rejected();
        // $project_hold     = $this->projectrepository->hold();

        $project_waiting  = $this->projectrepository->getWhere([['status', 'waiting'], ['charity_id', $this->user->id]]);
        $project_approved = $this->projectrepository->getWhere([['status', 'approved'], ['charity_id', $this->user->id]]);
        $project_rejected = $this->projectrepository->getWhere([['status', 'rejected'], ['charity_id', $this->user->id]]);
        $project_hold     = $this->projectrepository->getWhere([['status', 'hold'], ['charity_id', $this->user->id]]);
        $user = $this->user;
        
        $projects = $user->projects()->where('profile', 0)->get();

        return view('charities.dashboard' , compact('sponsers' , 'cost_donate' , 'phases' , 'project_waiting' , 
            'project_approved' , 'project_hold' , 'project_rejected', 'user', 'projects'));

    } // end of class

} // end of class

app/Http/Controllers/Charity/ExchangeController.php
<?php

namespace App\Http\Controllers\Charity;

use App\Http\Controllers\Controller;
use App\Repositories\FinancialRequestRepositoryInterface;
use App\Repositories\NotificationRepositoryInterface;
use Illuminate\Http\Request;

class ExchangeController extends Controller
{

    public $financialrepository;
    public $notificationRepository;

    public function __construct(FinancialRequestRepositoryInterface $financialrepository,
                                NotificationRepositoryInterface $notificationRepository)
    {

        $this->financialrepository = $financialrepository;
        $this->notificationRepository = $notificationRepository;

        $this->middleware(function ($request, $next) {

            if(auth()->user()->hasRole('charity_employee')){

                $this->user = auth()->user()->charity;
            }
            else{
                
                $this->user = auth()->user();
            }

            return $next($request);
        });
        
    } // end of construct

    public function BondExchange()
    {

        if(!checkPermissions(['list_exchange_bonds_'.$this->user->id])){

            session()->flash('error', trans('admin.do_not_have_permission'));

            return redirect()->back();
        }

        // delete notifications
        $this->notificationRepository->deleteWhere([['title', 'acceptbondexchange']]);

        $financial_requests = $this->financialrepository->getWhereWith(['requestable', 'project', 'currency'], 
                [['requestable_id' , $this->user->id] , ['bank_account_num' , '!=' , null] , ['voucher_num' ,'!=' , null] , [
                    'status' , 'approved'] , ['type' , 'exchange'], ['recieve_status', 'paid']]);

        return view('charities.orders.bond-exchange.index' , compact('financial_requests'));

    }

    public function orderExchange()
    {

        $financial_requests = $this->financialrepository->getWhere([['requestable_id' , $this->user->user()->id] , ['bank_account_num' , null] , ['status' , 'approved'] , ['voucher_num' , null] , ['type' , 'exchange']]);

        return view('charities.orders.order-exchange.index' , compact('financial_requests'));

    }    

    public function acceptBond(Request $request)
    {
        
        if(!checkPermissions(['list_exchange_bonds_'.$this->user->id])){

            session()->flash('error', trans('admin.do_not_have_permission'));

            return redirect()->back();
        }

        $updated = $this->financialrepository->update(['recieve_status' => $request->recieve_status] , $request->id);

        if($updated){

            return response()->json(['data' => 1], 200);
        }
        else{

            return response()->json(['data' => 0], 200);
        }

    }


} // end of class

resources/views/charities/employees/index.blade.php
@extends('layout.app')

@section('title', trans('admin.employees'))
@section('description', trans('admin.home'))
@section('image', asset('dashboard/app-assets/images/logo.png'))

@section('content')

<!-- Basic table -->
<section id="basic-datatable">
    <div class="row">
        <div class="col-12">
            <div class="card">
                @if(checkPermissions(['create_employees_'.auth()->user()->id]))
                    <a href="{{route('charity.employees.create')}}" class="btn btn-primary">{{trans('admin.create')}}</a>
                @endif            
                <div class="card-datatable table-responsive">
                    <table class="datatables-basic table">
                    <thead>
                        <tr>
                            <th>{{trans('admin.id')}}</th>
                            <th>{{trans('admin.name_employee_ar')}}</th>
                            <th>{{trans('admin.name_employee_en')}}</th>
                            <th>{{trans('admin.nation_number')}}</th>
                            <th>{{trans('admin.country')}}</th>
                            {{-- <th>{{ trans('admin.show') }}</th> --}}
                            <th>{{trans('admin.actions')}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($employees as $employee)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $employee->name_ar }}</td>
                                <td>{{ $employee->name_en }}</td>
                                <td>{{ $employee->nation_number }}</td>
                                <td>{{ Countries::getOne($employee->country, \App::getLocale()) }}</td>
                                <td>
                                    @if(checkPermissions(['show_employees_'.auth()->user()->id]))
                                        <a  href="{{route('charity.employees.show', $employee->slug)}}" title="{{trans('admin.show')}}">
                                            <i data-feather="eye" class="mr-50"></i>
                                        </a>
                                    @endif
                               
                                    @if(checkPermissions(['edit_employees_'.auth()->user()->id]) || checkPermissions(['delete_employees_'.auth()->user()->id]))
                                 
                                                @if(checkPermissions(['edit_employees_'.auth()->user()->id]))
                                                    <a  href="{{route('charity.employees.edit', $employee->slug)}}" title="{{trans('admin.edit')}}">
                                                        <i data-feather="edit-2" class="mr-50"></i>
                                                     </a>
                                                @endif
                                                @if(checkPermissions(['delete_employees_'.auth()->user()->id]))
                                                    <a class="remove-table" title="{{trans('admin.delete')}}" href="javascript:void(0);" data-url="{{route('charity.employees.destroy', $employee->id)}}">
                                                        <i data-feather="trash" class="mr-50"></i>
                                                    </a>
                                                @endif
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                </div>
                {{$employees->links()}}
            </div>
        </div>
    </div>
    
</section>
<!--/ Basic table -->

@endsection


@push('js')
    <script src="{{asset('dashboard/forms/main/change-status.js')}}"></script>
@endpush

resources/views/charities/employees/jopOfJopCategory.blade.php
@foreach($jops as $jop)
    <option value="{{ $jop->id }}" {{ old('job_id') }}>{{ $jop->name }}</option>
@endforeach

resources/views/charities/employees/show.blade.php
@extends('layout.app')

@section('title', trans('admin.show-charity'))
@section('description', trans('admin.home'))
@section('image', asset('dashboard/app-assets/images/logo.png'))

@section('content')

    <section class="app-user-view">
        <!-- Charity Card & Plan Starts -->
        <div class="row">
            <!-- Charity Card starts-->
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="card user-card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-6 col-lg-12 d-flex flex-column justify-content-between border-container-lg">
                                <div class="user-avatar-section">
                                    <div class="d-flex justify-content-start">
                                        <img class="img-fluid rounded" src="{{asset('dashboard/images/avatar.png')}}" height="70" width="70" alt="{{$employee->name}}" />
                                        <div class="d-flex flex-column ml-1">
                                            <div class="user-info mb-1">
                                                <h4 class="mb-0">{{$employee->name}}</h4>
                                                <span class="card-text">{{$employee->email}}</span><br>
                                                <span class="card-text">{{Countries::getOne($employee->country, \App::getLocale())}}</span><br>
                                                <span class="card-text">{{$employee->city}}</span>
                                            </div>
                                            <div class="d-flex flex-wrap">
                                                @if(checkPermissions(['edit_emp']))

                                                    <a href="{{route('admin.employees.edit', $employee->slug)}}" class="btn btn-primary">{{trans('admin.edit')}}</a>
                                               
                                                @endif
                                            
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="col-xl-6 col-lg-12 mt-2 mt-xl-0">
                                <div class="user-info-wrapper">
                                    <div class="d-flex flex-wrap">
                                        <div class="user-info-title">
                                            <i data-feather="chrome" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.nationality')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->nationality->name}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap">
                                        <div class="user-info-title">
                                            <i data-feather="chrome" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.nation_number')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->nation_number}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="check" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.region')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->region}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="star" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.street')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->street}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="flag" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.unit_number')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->unit_number}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="flag" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.mail_box')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->mail_box}}</p>
                                    </div>
                                    <div class="d-flex flex-wrap">
                                        <div class="user-info-title">
                                            <i data-feather="phone" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.postal_code')}}</span>
                                        </div>
                                        <p class="card-text mb-0" dir="ltr">
                                            {{$employee->postal_code}}
                                        </p>
                                    </div>
                                    <div class="d-flex flex-wrap">
                                        <div class="user-info-title">
                                            <i data-feather="phone" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.phone')}}</span>
                                        </div>
                                        <p class="card-text mb-0">
                                            {{$employee->phone}}
                                        </p>
                                    </div>
                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="flag" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.contract_start_date')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->contract_start_date}}</p>
                                    </div>

                                    <div class="d-flex flex-wrap my-50">
                                        <div class="user-info-title">
                                            <i data-feather="flag" class="mr-1"></i>
                                            <span class="card-text text-primary user-info-title font-weight-bold mb-1 mr-1">{{trans('admin.contract_end_date')}}</span>
                                        </div>
                                        <p class="card-text mb-0">{{$employee->contract_end_date}}</p>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Charity Card Ends-->

            <!-- charity categories Card starts-->
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="card plan-card border-primary">
                    <div class="card-header d-flex justify-content-between align-items-center pt-75 pb-1">
                        <h5 class="mb-0 badge badge-light-primary">{{trans('admin.permissions')}}</h5>
                        
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @forelse ($employee->permissions as $permission)
                                <div class="col-lg-4 col-sm-6 mb-2">{{ __('admin.' . substr($permission->name, 0, -2)) }}</div> 
                            @empty
                                <div class="col-lg-4 col-sm-6 mb-2">{{trans('admin.no_data')}}</div>
                            @endforelse
                        </ul>
                        <br>
                    </div>
                </div>
            </div>
            <!-- /charity categories CardEnds -->
            
        </div>
        <!-- Charity Card & Plan Ends -->

    </section>

@endsection

@push('js')
    <script src="{{asset('dashboard/forms/main/change-status.js')}}"></script>
@endpush