routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\StaticPageController;

// Begin: route namespace charity
// route login charity and admin

// AUTH ROUTES
Route::namespace('Auth')->middleware(['guest', 'lang'])->group(function(){
    // login
    Route::get('login/{role?}' , 'LoginController@login')->name('admin.login');
    Route::post('login/auth' , 'LoginController@loginAuth')->name('login.auth');
    
    Route::get('authorized'      , 'AuthorizedConrtoller@authorized')->name('authorized');
    Route::get('return-authorized'      , 'AuthorizedConrtoller@returnAuthorized')->name('return.authorized');

    // Forgot password routes
    Route::get('forgot-password' , 'PasswordController@getPasswordForm')->name('forgot-password');
    Route::post('send-link', 'PasswordController@sendResetPasswordLink')->name('send-reset-password-link');
    Route::get('reset-password/{email}/{role}', 'PasswordController@resetPassword')->name('reset-password');
    Route::post('store-new-password', 'PasswordController@storeNewPassword')->name('store-new-password');
    
});

Route::namespace('Auth')->group(function(){
    // route logout
    Route::get('logout' , 'LoginController@logout')->name('admin.logout')->middleware('lang');
    // route take token firebase
    Route::post('save-token' , 'UserController@saveToken')->name('save-token');

});

// Change language
Route::get('lang/{lang}', 'Web\MainController@lang')->name('lang');

// Get charity category services
Route::post('get-category-services', 'Web\MainController@getCategoryServices')->name('get-category-services')->middleware('lang');
Route::post('get-service-features', 'Web\MainController@getServiceFeatures')->name('get-service-features')->middleware('lang');


//------------------------------------------------------------------------------------------------------------------------------------------------




// BEGIN: CHARITY ROUTES
Route::middleware(['role:charity|charity_employee', 'auth:charity' , 'lang'])->prefix('charity')->name('charity.')->namespace('Charity')->group(function() {

    // route index dashbaord
    Route::get('/dashboard' , 'DashboardController@index')->name('dashboard');
    // route profile
    Route::get('/dashboard/profile' , 'ProfileController@index')->name('dashboard.profile');
    Route::get('/dashboard/profile/edit' , 'ProfileController@edit')->name('dashboard.profile.edit');
    Route::put('/dashboard/profile/update' , 'ProfileController@update')->name('dashboard.profile.update');
    // route charities
    Route::resource('charities' , 'CharityController');      
    Route::post('send/request/edit/charity' , 'ProfileController@sendRequestEdit')->name('send.request.edit.charity');
    
    // Employee edit profile request
    Route::get('profile-edit', 'ProfileController@editEmployeeProfile')->name('emp-profile.edit');
    Route::put('profile-update', 'ProfileController@UpdateEmployeeProfile')->name('emp-profile.update');

    // change currency             
    Route::get('exchange/{currency_id}', [App\Http\Controllers\Admin\MainController::class, 'exchangeCurrency'])->name('main.exchange_currency');
    // route contact charity
    Route::get('/contract' , 'ProfileController@contract')->name('contract');
    Route::post('/signature' , 'ProfileController@signature')->name('signature');
    
    Route::middleware(['contract' , 'status'])->group(function() {

        // route projects
        Route::resource('projects' , 'ProjectController'); 
        Route::post('send/request/edit' , 'ProjectController@sendRequestEdit')->name('send.request.edit');              
        Route::get('delete/image/project' , 'ProjectController@deleteImage')->name('delete.image.project');              
        // route phases
        Route::resource('phases' , 'PhasesController');    
        Route::get('get/start/date/project' , 'PhasesController@getStartDateProject')->name('get.start.date.project');              
        // route report
        Route::resource('reports' , 'ReportController');              
        Route::get('delete/image' , 'ReportController@deleteImage')->name('delete.image');              
        Route::get('phase/{id}/{type}' , 'ReportController@create')->name('phase');  
        // sponsers
        Route::resource('sponsers' , 'SponserController');              
        // route cities of country
        Route::get('cities' , 'CityController@cityOfCountry')->name('cities');
          
        // exchange
        Route::get('order/exchange' , 'ExchangeController@orderExchange')->name('order.exchange');              
        Route::get('bond/exchange' , 'ExchangeController@BondExchange')->name('bond.exchange');              
        Route::post('accept/bond' , 'ExchangeController@acceptBond')->name('accept.bond');  
        
        // route employee
        Route::resource('employees' , 'EmployeeController');

        // route Job categories
        Route::resource('job-categories' , 'JobCategoryController');
        // jop of jop category
        Route::get('jop/jopCategory' , 'JobCategoryController@jopOfJopCategory')->name('jop.jopCategory');

        // route Jobs
        Route::resource('jobs' , 'JobController');

        // Degrees route
        Route::resource('degrees' , 'DegreeController');

        // Nationalities route
        Route::resource('nationalities' , 'NationalityController');
        
     });


      
}); // END: CHARITY ROUTES



//--------------------------------------------------------------------------------------------------------------------------------------------------




// BEGIN: ADMIN ROUTES
Route::middleware(['role:admin|employee' , 'auth:web', 'lang'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

    // Admin home
    Route::get('/' , 'HomeController@index')->name('home');

    //Main Controller
    Route::post('get-diff-days', [App\Http\Controllers\Admin\MainController::class, 'diffDays'])->name('get-diff-days');
    Route::post('change-status', [App\Http\Controllers\Admin\MainController::class, 'changeStatus'])->name('main.change-status');
    Route::post('delete-image', [App\Http\Controllers\Admin\MainController::class, 'deleteImage'])->name('main.delete-image');
    Route::get('exchange/{currency_id}', [App\Http\Controllers\Admin\MainController::class, 'exchangeCurrency'])->name('main.exchange_currency');

    // Profile (Admin + Employee)
    Route::get('profile', [App\Http\Controllers\Admin\MainController::class, 'editProfile'])->name('profile.edit');
    Route::put('profile/{id}', [App\Http\Controllers\Admin\MainController::class, 'updateProfile'])->name('profile.update');


    // Static Pages
    Route::get('static-pages', [StaticPageController::class, 'getStaticPagesByNation'])->name('static-pages.index');
    Route::get('static-pages/{id}/edit', [StaticPageController::class, 'edit'])->name('static-pages.edit');
    Route::patch('static-pages/{id}', [StaticPageController::class, 'update'])->name('static-pages.update');

    // Slider
    Route::resource('sliders', SliderController::class)->except(['index', 'show']);
    Route::get('sliders', [App\Http\Controllers\Admin\SliderController::class, 'index'])->name('sliders.index');

    // Charities
    Route::get('charities-status/{status}', [App\Http\Controllers\Admin\CharityController::class, 'getCharityWithStatus'])->name('charities.get-with-status');
    Route::get('export-all-charities/{status}', [App\Http\Controllers\Admin\CharityController::class, 'exportAll'])->name('export-all-charities');
    Route::get('export-charity/{id}', [App\Http\Controllers\Admin\CharityController::class, 'exportCharity'])->name('export-charity');

    
    // Projects Sponsers
    Route::get('sponsers/{project_id}', [App\Http\Controllers\Admin\SponserController::class, 'create'])->name('sponsers.create');
    Route::post('sponsers', [App\Http\Controllers\Admin\SponserController::class, 'store'])->name('sponsers.store');
    Route::put('sponsers/{id}', [App\Http\Controllers\Admin\SponserController::class, 'update'])->name('sponsers.update');
    Route::delete('sponsers/{id}', [App\Http\Controllers\Admin\SponserController::class, 'destroy'])->name('sponsers.destroy');

    // Project Phases
    Route::get('phases/{project_id}', [App\Http\Controllers\Admin\PhaseController::class, 'create'])->name('phases.create');
    Route::get('phases/{id}/show', [App\Http\Controllers\Admin\PhaseController::class, 'show'])->name('phases.show');
    Route::post('phases', [App\Http\Controllers\Admin\PhaseController::class, 'store'])->name('phases.store');
    Route::get('phases/{id}/edit', [App\Http\Controllers\Admin\PhaseController::class, 'edit'])->name('phases.edit');
    Route::put('phases/{id}/update', [App\Http\Controllers\Admin\PhaseController::class, 'update'])->name('phases.update');
    Route::delete('phases/{id}/delete', [App\Http\Controllers\Admin\PhaseController::class, 'destroy'])->name('phases.destroy');

    // Resources contrllers
    // contacts
    Route::resource('contacts', ContactController::class)->only(['index', 'destroy']);

    // projects
    Route::get('projects-status/{status}', [App\Http\Controllers\Admin\ProjectController::class, 'getProjectWithStatus'])->name('projects.get-project-with-status');
    Route::post('projects-edit-request', [App\Http\Controllers\Admin\MainController::class, 'changeStatus'])->name('projects-edit-request');
    Route::post('projects/delete-image', [App\Http\Controllers\Admin\ProjectController::class, 'deleteImage'])->name('projects.delete-image');
    Route::get('projects/restore/{id}', [App\Http\Controllers\Admin\ProjectController::class, 'restore'])->name('projects.restore');
    Route::get('export-all-projects/{status}', [App\Http\Controllers\Admin\ProjectController::class, 'exportAll'])->name('export-all-projects');
    Route::get('export-project/{id}', [App\Http\Controllers\Admin\ProjectController::class, 'exportProject'])->name('export-project');

app/Http/Controllers/Admin/SponserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repositories\SponserRepositoryInterface;
use App\Repositories\WorkFieldRepositoryInterface;
use App\Http\Requests\Admin\SponserRequest;
use Illuminate\Http\Request;

class SponserController extends Controller
{
    private $workFieldRepository;
    private $sponserRepository;

    public function __construct(WorkFieldRepositoryInterface $workFieldRepository,
                                SponserRepositoryInterface $sponserRepository){

        $this->workFieldRepository = $workFieldRepository;
        $this->sponserRepository = $sponserRepository;
    }

    public function create($project_id){

        if(!checkPermissions(['edit_project_data'])){

            session()->flash('error', trans('admin.do_not_have_permission'));

            return redirect()->back();
        }

        $nation_id = getAuthNationId();

        $data['work_fields'] = $this->workFieldRepository->getWhere([['nation_id', $nation_id]]);
        $data['project_id'] = $project_id;

        return view('admin.sponsers.create')->with([
            'data' => $data
        ]);
    }

    public function store(SponserRequest $request){

        if(!checkPermissions(['edit_project_data'])){

            session()->flash('error', trans('admin.do_not_have_permission'));

            return redirect()->back();
        }

        $data['project_id'] = $request->project_id;
        $data['name_ar'] = $request->sponser_name_ar;
        $data['name_en'] = $request->sponser_name_en;
        $data['work_field_id'] = $request->sponser_work_field_id;

        $sponser = $this->sponserRepository->create($data);

        if($sponser){

            session()->flash('success', trans('admin.add_success'));

            return redirect()->route('admin.projects.edit', $request->project_id);
        }
        else{

            session()->flash('error', trans('admin.add_error'));

            return redirect()->route('admin.projects.edit', $request->project_id);
        }

    }

    public function update(SponserRequest $request, $id){

        if(!checkPermissions(['edit_project_data'])){

            session()->flash('error', trans('admin.do_not_have_permission'));

            return redirect()->back();
        }

        $data['project_id'] = $request->project_id;
        $data['name_ar'] = $request->sponser_name_ar;
        $data['name_en'] = $request->sponser_name_en;
        $data['work_field_id'] = $request->sponser_work_field_id;

        $updated = $this->sponserRepository->update($data, $id);

        $sponser = $this->sponserRepository->findOne($id);

        if($updated){

            session()->flash('success', trans('admin.update_success'));

            return redirect()->route('admin.projects.edit', $sponser->project_id);
        }
        else{

            session()->flash('error', trans('admin.add_error'));

            return redirect()->route('admin.projects.edit', $request->project_id);
        }
    }

    public function destroy($id){

        if(!checkPermissions(['edit_project_data'])){

            return response()->json(['data' => 2], 200);
        }

        // delete sponser
        $deleted = $this->sponserRepository->delete($id);

        if($deleted){

            return response()->json(['data' => 1], 200);
        }
        else{

            return response()->json(['data' => 0], 200);
        }


    }
}

app/Http/Controllers/Charity/CityController.php
<?php

namespace App\Http\Controllers\Charity;

use App\Http\Controllers\Controller;
use App\Repositories\CityRepositoryInterface;
use Illuminate\Http\Request;

class CityController extends Controller
{
    
    public $cityrepository;
   
    public function __construct(CityRepositoryInterface $cityrepository)
    {

        $this->cityrepository    = $cityrepository;
        
    } // end of construct
    
    public function cityOfCountry(Request $request)
    {

        $nation_id = getNationId();

        $cities = $this->cityrepository->getWhere([['nation_id', $nation_id], ['parent_id', $request->id]]);

        return view('charities.projects.cities' , compact('cities'))->render();

    } // end of index    

}

app/Http/Controllers/Charity/DashboardController.php
<?php

namespace App\Http\Controllers\Charity;

use App\Http\Controllers\Controller;
use App\Repositories\PhaseRepositoryInterface;
use App\Repositories\ProjectRepositoryInterface;
use App\Repositories\ProjectUserRepositoryInterface;
use App\Repositories\SponserRepositoryInterface;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public $projectrepository;
    public $sponserrepository;
    public $phasesrepository;
    public $projectuserrepository;

    public function __construct(ProjectRepositoryInterface $projectrepository ,
                                SponserRepositoryInterface $sponserrepository,
                                PhaseRepositoryInterface $phasesrepository,
                                ProjectUserRepositoryInterface $projectuserrepository
                                )
    {
     
        $this->projectrepository     = $projectrepository;
        $this->sponserrepository     = $sponserrepository;
        $this->phasesrepository      = $phasesrepository;
        $this->projectuserrepository = $projectuserrepository;

        $this->middleware(function ($request, $next) {

            if(auth()->user()->hasRole('charity_employee')){

                $this->user = auth()->user()->charity;
            }
            else{
                
                $this->user = auth()->user();
            }

            return $next($request);
        });
        
    }

    public function index()
    {
        // if(auth()->user()->hasRole('charity_employee')){
        //     $user = auth()->user()->charity;
        // }
        // else{

        //     $user = auth()->user();
        // }

        // dd(checkPermissions(['list_projects_'.$user->id]) || checkPermissions(['create_projects_'.$user->id]) || 
        // checkPermissions(['edit_projects_'.$user->id]) || checkPermissions(['show_projects_'.$user->id]) || 
        // checkPermissions(['delete_projects_'.$user->id]) ||
        // checkPermissions(['list_phases_'.$user->id]) || checkPermissions(['create_phases_'.$user->id]) || 
        // checkPermissions(['edit_phases_'.$user->id]) || checkPermissions(['show_phases_'.$user->id]) || 
        // checkPermissions(['delete_phases_'.$user->id]));

        $ids      = $this->user->projects()->pluck('id');
        $sponsers = $this->sponserrepository->count($ids);
        $phases   = $this->phasesrepository->count($ids);
        $cost_donate = $this->projectuserrepository->costAllProject($ids);

        // get status projects
        // $project_waiting  = $this->projectrepository->waiting();
        // $project_approved = $this->projectrepository->approved();
        // $project_rejected = $this->projectrepository->rejected();
        // $project_hold     = $this->projectrepository->hold();

        $project_waiting  = $this->projectrepository->getWhere([['status', 'waiting'], ['charity_id', $this->user->id]]);
        $project_approved = $this->projectrepository->getWhere([['status', 'approved'], ['charity_id', $this->user->id]]);
        $project_rejected = $this->projectrepository->getWhere([['status', 'rejected'], ['charity_id', $this->user->id]]);
        $project_hold     = $this->projectrepository->getWhere([['status', 'hold'], ['charity_id', $this->user->id]]);
        $user = $this->user;
        
        $projects = $user->projects()->where('profile', 0)->get();

        return view('charities.dashboard' , compact('sponsers' , 'cost_donate' , 'phases' , 'project_waiting' , 
            'project_approved' , 'project_hold' , 'project_rejected', 'user', 'projects'));

    } // end of class

} // end of class

resources/views/charities/sponsers/create.blade.php
@extends('layout.app')
@section('title')
{{ __('admin.add_sponser') }}
@endsection
@section('content')


    <!-- Validation -->
    <section class="bs-validation">
        <div class="row">

            <!-- jQuery Validation -->
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ __('admin.create') }}</h4>
                    </div>
                    <div class="card-body">

                        <form id="form-sponser" method="post" enctype="multipart/form-data">

                            <!-- NAME PROJECT -->
                            <div class="form-group">
                                <label for="select-country">{{ __('admin.num_project') }}</label>
                                <select class="form-control" id="project_id" url="{{ route('charity.get.start.date.project') }}" name="project_id" required>
                                    <option value="">{{ __('admin.choose_project') }}</option>

                                    @foreach($projects as $project)

                                        <option value="{{ $project->id }}">{{ $project->project_num }}</option>

                                    @endforeach
                                </select>
                                <span class="error-input"></span>
                            </div>
                            

                                
                            <!-- ORDER -->
                            <div class="form-group">
                                <label for="select-country">{{ __('admin.work') }}</label>
                                <select class="form-control" id="work_field_id" name="work_field_id" required>
                                    <option value="">{{ __('admin.choose_work') }}</option>

                                    @foreach($works as $key=>$work)

                                        <option value="{{ $work->id }}">{{ $work->name }}</option>

                                    @endforeach

                                </select>
                                <span class="error-input"></span>
                            </div>


                            <div class="row">


                                <!-- NAME AR -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="name_ar">{{ __('admin.name_sponser_ar') }}</label>
                                        <input type="text" id="name_sponser_ar" name="name_sponser_ar" class="form-control" placeholder="{{ __('admin.name_sponser_ar') }}" />
                                        <span class="error-input"></span>
                                    </div> 
                                </div> 
                                
                                <!-- NAME EN -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="name_sponser_en">{{ __('admin.name_sponser_en') }}</label>
                                        <input type="text" id="name_sponser_en" name="name_sponser_en" class="form-control" placeholder="{{ __('admin.name_sponser_en') }}" />
                                        <span class="error-input"></span>
                                    </div> 
                                </div>                             

                            </div>                                                       

                        
                            <div class="row">
                                <div class="col-12">
                                    <button type="button" id="click-form-sponser" redirect="" url="{{ route('charity.sponsers.store') }}" class="btn btn-primary" name="submit" value="Submit">{{ __('admin.create') }} </button>
                                </div>
                                                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /jQuery Validation -->


        </div>
    </section>
    <!-- /Validation -->





@endsection

@section('scripts')

    <script src="{{ url('charity/js/sponsers/create.js') }}"></script>
    <script src="{{ url('custom/custom-validate.js') }}"></script>
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>

@endsection

resources/views/charities/sponsers/edit.blade.php
@extends('layout.app')
@section('title')
{{ __('admin.edit_sponser') }}
@endsection
@section('content')


    <!-- Validation -->
    <section class="bs-validation">
        <div class="row">

            <!-- jQuery Validation -->
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ __('admin.edit') }}</h4>
                    </div>
                    <div class="card-body">

                        <form id="form-sponser" method="post" enctype="multipart/form-data">

                        <input type="hidden" id="item" name="item" value="{{ $sponserOne->id }}" class="" />

                            <!-- NAME PROJECT -->
                            <div class="form-group">
                                <label for="select-country">{{ __('admin.num_project') }}</label>
                                <select class="form-control" id="project_id" url="{{ route('charity.get.start.date.project') }}" name="project_id">
                                    <option value="">{{ __('admin.choose_project') }}</option>

                                    @foreach($projects as $project)

                                        <option value="{{ $project->id }}" {{ $sponserOne->project_id == $project->id ? 'selected' : old('work_field_id') }} >{{ $project->project_num }}</option>

                                    @endforeach
                                </select>
                                <span class="error-input"></span>
                            </div>
                            

                                
                            <!-- ORDER -->
                            <div class="form-group">
                                <label for="select-country">{{ __('admin.work') }}</label>
                                <select class="form-control" id="work_field_id" name="work_field_id">
                                    <option value="">{{ __('admin.choose_work') }}</option>

                                    @foreach($works as $key=>$work)

                                        <option value="{{ $work->id }}" {{ $sponserOne->work_field_id == $work->id ? 'selected' : old('work_field_id') }} >{{ $work->name }}</option>

                                    @endforeach

                                </select>
                                <span class="error-input"></span>
                            </div>


                            <div class="row">


                                <!-- NAME AR -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="name_ar">{{ __('admin.name_sponser_ar') }}</label>
                                        <input type="text" id="name_sponser_ar" name="name_sponser_ar" class="form-control" value="{{ $sponserOne->name_ar ? $sponserOne->name_ar : old('name_ar') }}" placeholder="{{ __('admin.name_sponser_ar') }}" />
                                        <span class="error-input"></span>
                                    </div> 
                                </div> 
                                
                                <!-- NAME EN -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-label" for="name_sponser_en">{{ __('admin.name_sponser_en') }}</label>
                                        <input type="text" id="name_sponser_en" name="name_sponser_en" class="form-control" value="{{ $sponserOne->name_en ? $sponserOne->name_en : old('name_en') }}" placeholder="{{ __('admin.name_sponser_en') }}" />
                                        <span class="error-input"></span>
                                    </div> 
                                </div>                             

                            </div>                          

                            <div class="row">
                                <div class="col-12">
                                    <button type="button" id="click-form-sponser" url="{{ route('charity.sponsers.update' , $sponserOne->id) }}" class="btn btn-primary" name="submit" value="Submit"><i data-feather="edit" class="mr-50"></i> {{ __('admin.edit') }} </button>
                                </div>
                                                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /jQuery Validation -->


        </div>
    </section>
    <!-- /Validation -->





@endsection

@section('scripts')

<script src="{{ url('charity/js/sponsers/edit.js') }}"></script>
<script src="{{ url('custom/custom-validate.js') }}"></script>
<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>

@endsection

resources/views/charities/sponsers/show.blade.php
@extends('layout.app')
@section('title')
{{ __('admin.sponsers') }}
@endsection
@section('content')


<section class="app-user-view">

    <!-- User Card & Plan Starts -->
    <div class="row">
        <!-- User Card starts-->
        <div class="col-xl-12">
            <div class="card user-card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6 col-lg-12 d-flex flex-column justify-content-between border-container-lg">
                            <div class="user-avatar-section">
                                <div class="d-flex justify-content-start">
                                    <div class="d-flex flex-column ml-1">
                                        <div class="user-info mb-1">
                                            <h4 class="mb-0">{{ $sponser_one->name }}</h4>
                                        </div>
                                        <div class="d-flex flex-wrap">
                                        
                                            @if(checkPermissions(['edit_sponser' . $sponser_one->id]))
                                                <a href="{{route('charity.phases.edit', $sponser_one->id)}}" class="btn btn-primary">{{ __('admin.edit') }}</a>
                                            @endif
                                            <!-- <a href="" class="btn btn-outline-danger ml-1">Edit</a> -->
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-xl-6 col-lg-12 mt-2 mt-xl-0">
                            <div class="user-info-wrapper">
                                <div class="d-flex flex-wrap">
                                    <div class="user-info-title">
                                        <i data-feather="check" class="mr-1"></i>
                                        <span class="card-text user-info-title font-weight-bold mb-0">{{ __('admin.name_sponser_ar') }}</span>
                                    </div>
                                    <p class="card-text mb-0 ml-2">{{ $sponser_one->name_ar }}</p>
                                </div>
                                <div class="d-flex flex-wrap my-50">
                                    <div class="user-info-title">
                                        <i data-feather="check" class="mr-1"></i>
                                        <span class="card-text user-info-title font-weight-bold mb-0">{{ __('admin.name_sponser_en') }}  </span>
                                    </div>
                                    <p class="card-text mb-0 ml-2">  {{ $sponser_one->name_en }} </p>
                                </div>
                                <div class="d-flex flex-wrap my-50">
                                    <div class="user-info-title">
                                        <i data-feather="check" class="mr-1"></i>
                                        <span class="card-text user-info-title font-weight-bold mb-0">{{ __('admin.work') }}  </span>
                                    </div>
                                    <p class="card-text mb-0 ml-2">  {{ $sponser_one->work_field->name }} </p>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /User Card Ends-->

    </div>
    <!-- User Card & Plan Ends -->

</section>


@endsection

@section('scripts')

<script>

    
</script>

@endsection