routes/web.php
    Route::get('financial-bills/{type}', [App\Http\Controllers\Admin\FinancialBillController::class, 'getBillByType'])->name('financial-bills');
    Route::get('financial-bills-exchange/{status}', [App\Http\Controllers\Admin\FinancialBillController::class, 'getBillByStatus'])->name('financial-bills-exchange');
    Route::get('financial-bills-catch/{status}', [App\Http\Controllers\Admin\FinancialBillController::class, 'getBillByStatus'])->name('financial-bills-catch');
    Route::post('get-charity-iban', [App\Http\Controllers\Admin\FinancialBillController::class, 'getCharityIban'])->name('get-charity-iban');
    Route::post('change-revceive-status', [App\Http\Controllers\Admin\FinancialBillController::class, 'changeRevceiveStatus'])->name('financial-bills.change-revceive-status');

    // Ambassadors
    Route::get('ambassadors', [App\Http\Controllers\Admin\AmbassadorController::class, 'index'])->name('ambassadors.index');

    // Edit logs
    Route::get('logs', [App\Http\Controllers\Admin\LogController::class, 'index'])->name('logs.index');


    Route::resources([

        'cities' => CityController::class,
        'job-categories' => JobCategoryController::class,
        'work-fields' => WorkFieldController::class,
        'charity-categories' => CharityCategoryController::class,
        'services' => ServiceController::class,
        'service-features' => ServiceFeatureController::class,
        'jobs' => JobController::class,
        'degrees' => DegreeController::class,
        'banks' => BankController::class,
        'charities' => CharityController::class,
        'nationalities' => NationalityController::class,
        'projects' => ProjectController::class,

    ]);

    // ahmed

    // Agreements
    Route::resource('agreements' , AgreementController::class)->only(['create', 'store']);
    // contracts
    Route::resource('contracts' , ContractController::class);
    // settings
    Route::resource('settings' , SettingController::class);
    Route::get('setting' , 'SettingController@edit')->name('setting.edit');
    Route::post('setting/{nation_id}/store' , 'SettingController@update')->name('setting.update'); 
    
    // project servcies
    Route::resource('services' , ServiceController::class);
    // route city
    Route::get('city/country' , 'CityController@cityOfCountry')->name('city.country');
    // jop of jop category
    Route::get('jop/jopCategory' , 'JobCategoryController@jopOfJopCategory')->name('jop.jopCategory');
    // route employee
    Route::resource('employees' , EmployeeController::class);
    // route question
    Route::resource('questions' , QuestionController::class);    
    // route campaigns
    Route::resource('campaigns' , CampaignGoalController::class);
    // route currence
    Route::resource('currencies' , CurrencyController::class);
    // route rating criterias
    Route::resource('rating-criterias' , RatingCriteriaController::class)->only(['edit', 'index' , 'update']);;

}); // END: ADMIN ROUTES

// Employee poltics agreements route
Route::post('agree-politics', [App\Http\Controllers\Admin\EmpAgreementController::class, 'saveAgreement'])->name('emp.agree');

// get exchage - catch voucher
Route::get('voucher/{slug}', [App\Http\Controllers\Admin\FinancialRequestController::class, 'getVoucher'])->name('get-voucher')->middleware('lang');


//-------------------------------------------------------------------------------------------------------------------------------------------------



// BEGIN: WEBSITE ROUTES
Route::get('/aff/{aff}', [App\Http\Controllers\Admin\MarketingController::class, 'aff'])->name('aff');

Route::name('web.')->namespace('Web')->middleware(['lang'])->group(function(){

    // comming soon
    // Route::get('/', function(){

    //     return view('logo');
    // });

    // Begin: route namespace web
    Route::get('/', 'HomeController@index')->name('home');
    // store contact ud
    Route::post('contact-us', 'HomeController@storeContactUs')->name('store-contact-us');
    // change currency 
    Route::get('/currency', 'MainController@currency')->name('currency');
    // project index
    Route::get('/projects', 'ProjectController@index')->name('projects');

    // category-projects
    Route::get('category/{slug}/projects', 'ProjectController@getCategoryProjects')->name('get-category-projects');

    // filter projects by country
    Route::get('filter-projects/{id}', 'MainController@filterProjectsByCountry')->name('projects.filter-projects-country');

    // project details
    Route::get('projects/{slug}', 'ProjectController@show')->name('projects.show');

    // rate project
    Route::post('rate-project/{slug}', 'ProjectController@rateProject')->name('projects.rate');
    
    // validate cost donate
    Route::post('/price-donate', 'DonateController@checkPrice')->name('price.donate');
    // sotre donate
    Route::post('/project/store', 'DonateController@store')->name('project.store');
    // store campaign
    Route::post('/campaign/store', 'AmbassadorController@store')->name('campaign.store');
    // get campaign
    Route::get('/campaign/{affiliate}', 'AmbassadorController@index')->name('campaign');
    
    // donate now
    Route::get('/donate', 'DonateController@index')->name('donate');
    Route::post('/get/project', 'DonateController@getProjectOfCategory')->name('get.project');
    Route::get('/check/project', 'DonateController@checkProject')->name('check.project');

    // statistics
    Route::get('/statistics', 'StatisticController@index')->name('statistics');

    // about
    Route::get('/about', 'StaticPageController@about')->name('about');

    // faq
    Route::get('/faq', 'StaticPageController@faq')->name('faq'); 

    // profile
    Route::get('/profile', 'ProfileController@index')->name('profile');      
    Route::get('/edit-profile', 'ProfileController@edit')->name('edit.profile');      
    Route::post('/update-profile', 'ProfileController@update')->name('update.profile');      
    Route::post('/upload/image', 'ProfileController@uploadImage')->name('upload.image');      
    Route::get('/profile/money', 'ProfileController@profileMoney')->name('profile.money');      
    Route::get('/profile/projects', 'ProfileController@profileProject')->name('profile.projects');      
    Route::post('/donate/month/update', 'ProfileController@updateDonateMonth')->name('donate.month.update');      
    Route::get('/donate/again', 'ProfileController@donateAgain')->name('donate.again');      
    Route::get('/delete/project', 'ProfileController@deleteProject')->name('delete.project');      
    Route::get('/profile/report', 'ProfileController@profileReport')->name('profile.report');      
    Route::get('/report/{slug}', 'ProfileController@report')->name('report');      
    Route::get('/report-details/{slug}', 'ProfileController@getReportDetails')->name('profile.get-report-details');      
    Route::get('/setting', 'ProfileController@setting')->name('setting');      
    Route::get('/active/notification', 'ProfileController@activeNotification')->name('active.notification');      
    Route::get('/delete/account', 'ProfileController@deleteAccount')->name('delete.account');      
    Route::get('profile/cart', 'ProfileController@getCart')->name('profile.cart');
    Route::post('profile/add-to-cart', 'ProfileController@addToCart')->name('profile.add-to-cart');
    
    // subscribe
    Route::post('subscribe', 'MainController@subscribe')->name('subscribe');

    
    // contact
    Route::get('/contact', 'ContactController@index')->name('contact');      
    Route::post('/contact/store', 'ContactController@store')->name('contact.store');      

    // Cart Routes
    Route::get('cart', 'CartController@index')->name('carts.index');
    Route::get('get-cart-items', 'CartController@getCartItems');
    Route::post('cart/add', 'CartController@store')->name('add-to-cart');
    Route::post('cart/{id}', 'CartController@removeItem')->name('cart.remove-item');

    // Notifications Routes
    Route::get('notifications', 'NotificationController@index')->name('notifications.index')->middleware('auth');
    Route::post('notifications/{id}', 'NotificationController@removeItem')->name('notifications.remove-item')->middleware('auth');

    // Register
    Route::get('register/{role}', 'RegisterController@getRegisterForm')->name('get-register-form')->middleware(['guest:charity', 'guest']);
    Route::post('register-donor', 'RegisterController@registerDonor')->name('register-donor')->middleware(['guest:charity', 'guest']);
    Route::post('register-charity', 'RegisterController@registerCharity')->name('register-charity')->middleware(['guest:charity', 'guest']);

    // Password
    Route::get('forgot-password/{role}', 'PasswordController@getEmailForm')->name('get-email-form');
    Route::post('send-verification-code/{role}', 'PasswordController@sendVerificationCode')->name('send-verification-code');
    Route::get('resend-code/{email}/{name}/{role}', 'PasswordController@sendCode')->name('resend-code');
    Route::post('verify', 'PasswordController@verify')->name('verify');
    Route::post('change-password', 'PasswordController@changePassword')->name('change-password');

    // Static pages
    Route::get('pages/{key}', 'StaticPageController@index')->name('pages');

    // Search
    Route::post('search', 'MainController@search')->name('search');
    

    Route::get('sendSMS', 'MainController@sendSms')->name('sendSMS');


});

Route::get('create-payment-session/{support_id}', [App\Http\Controllers\Web\PaymentController::class, 'createPaymentSession'])->name('create-payment-session');
Route::get('payment-success', [App\Http\Controllers\Web\PaymentController::class, 'success'])->name('payment.success')->middleware('lang');
Route::get('payment-cancle', [App\Http\Controllers\Web\PaymentController::class, 'cancle'])->name('payment.cancle')->middleware('lang');

resources/views/web/donates/donate.blade.php
@extends('web.layout.app')

@section('title', __('web.donate_now') )
@section('description', __('web.donate_now') )
@section('image', asset('web/images/main/white-logo.png'))


@section('content')


<!-- BEDIN: header -->

@include('web.donates.header')

<!-- END: header -->

<div class="main-content">
        {{-- <div class="hidden-title">
            <h2 class="white-text bold-text text-upper text-center page-title">{{ __('web.donate_now') }}</h2>
        </div> --}}
        <!-- start donate-pg
         ================ -->
         <section class="faq-page margin-div">
            <div class="container">
                <div class="row">
                    <div class="col-12">

                        @php
                            if(auth()->check()){

                                $donor_total_supports = auth()->user()->donor_total_supports;
                            }
                            else{
                                $donor_total_supports = 0;
                            }
                        @endphp

                        <div class="section-title first_color" data-aos="fade-in">
                            <div class="side-img"><img src="{{ url('web/images/icons/menu/8.png') }}" alt="icon"></div>
                            <h3 class="second_color text-cap bold-text">{{ __('web.donate_now') }}</h3>
                            <h4 class="text-upper bold-text">{{ __('web.donate_now') }}</h4>
                        </div>
                        <div class="donate-div text-center margin-div side-section">

                            {{-- <span style="color: #3dbecb;">{{__('web.cost_min')}}: {{$cost_min}} {{currencySymbol(session('currency'))}}</span> --}}
                            
                            <form action="#" class="donate-form" id="donate-cost-error-1">

                                <div class="donate-quantity" data-aos="zoom-out">
                                    <div class="form-group number-input-div">
                                        <span class="minus-num  numb-control">-</span>
                                        <input type="number" step=".01"
                                            class="form-control no_apperance_number number-input sm-raduis-input"
                                            name="number-input" minlength="2" maxlength="7" value="{{ $cost_min }}" pattern="\d{5}"
                                            required>
                                        <span class="plus-num numb-control">+</span>
                                    </div>

                                    <div class="form-group">
                                        <select class="form-control select-input sm-raduis-input currency_id" name="currency"
                                            required>
                                                @foreach($currencies as $currency)
                                                    <option value="{{ $currency->id }}" {{ $currency->id == session('currency') ? 'selected' : '' }}>{{ $currency->name }}</option>
                                                @endforeach
                                        </select>
                                    </div>

                                </div>
                                <span class="custom-error error"></span>

                                <div class="multi-checkboxes" data-aos="zoom-out">
                                    <div class="row justify-content-center">

                                        <div class="col-xl-3 col-sm-6 md-center">
                                            <div class="form-group">
                                                <div class="custom-checkbox circle-checkbox">
                                                    <input type="radio" class="hidden-input type-donate" name="donate_time" required
                                                        value="once" id="check_1">
                                                    <label for="check_1" class="dark-text"> <span>{{ __('web.once') }}
                                                        </span></label>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-xl-3 col-sm-6 md-center">
                                            <div class="form-group">
                                                <div class="custom-checkbox circle-checkbox">
                                                    <input type="radio" class="hidden-input type-donate" name="donate_time" required
                                                        value="month" id="check_2">
                                                    <label for="check_2" class="dark-text"><span>{{ __('web.monthly_deduction') }}</span></label>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-xl-3 col-sm-6 md-center">
                                            <div class="form-group">
                                                <div class="custom-checkbox circle-checkbox">
                                                    <!--don`t change id for that-->
                                                    <input type="radio" class="hidden-input type-donate" name="donate_time" required
                                                        value="gift" id="check_3">
                                                    <label for="check_3" class="dark-text"><span> {{ __('web.Donate as a Gift') }}</span></label>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-xl-3 col-sm-6 md-center">
                                            <div class="form-group">
                                                <div class="custom-checkbox circle-checkbox">
                                                    <input type="radio" class="hidden-input type-donate" name="donate_time" required
                                                        value="ambassador" id="check_4">
                                                    <label for="check_4" class="dark-text"> <span>{{ __('web.Be an Ambassador') }}</span></label>
                                                </div>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                                <div class="donate-cat gray-form text-left-dir">

                                    <div data-aos="zoom-out">
                                        <div class="form-group">
                                            <select class="form-control select-input" data-action="{{ route('web.get.project') }}" id="get_project" name="categories" required>
                                                <option selected disabled></option>
                                                    @foreach($charitycategories as $charitycategory)
                                                        <option value="{{ $charitycategory->id }}">{{ $charitycategory->name }}</option>
                                                    @endforeach
                                            </select>
                                            <label class="moving-label">{{ __('web.categories') }}</label>
                                        </div>


                                        <div class="form-group" id="append_project">

                                        </div>


                                        <div class="btn-div text-center">
                                        
                                            @if(auth()->guard('charity')->user())
                                                <button type="button" class=" sm-raduis white-btn auth-charity"><span>{{ __('web.donate_now') }}</span></button>
                                            @else
                                                <button 
                                                    type="button" 
                                                    id="donate-now" 
                                                    data-id="1" 
                                                    @if($donor_total_supports < 10000)  {{-- user can not donate if hist total donations is 10000 GBP a year --}}
                                                        data-action="{{ route('web.price.donate') }}" 
                                                    @endif
                                                    class="donate-prog-btn custom-btn sm-raduis white-btn
                                                    @if($donor_total_supports >= 10000) user_donation_full @endif"><span>{{ __('web.donate_now') }}</span></button>
                                            @endif
                                            {{-- <button type="button" class="simple-btn tooltip-link add-to-cart-num"
                                                title="add to cart"><img src="{{ url('web/images/icons/menu/shopping-cart.png') }}"
                                                    alt="img"></button> --}}
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--end donate-->


<!--start select-modals-->

<!--once modal-->
@include('web.donate_popups.once')

<!--gift modal-->
@include('web.donate_popups.gift')

<!--month modal-->
@include('web.donate_popups.monthly')

<!--ambassador modal-->
@include('web.donate_popups.ambassador')
<!--end select-modal-->
</div>
@endsection

@push('js')


    
    @if(\App::getLocale() == 'ar')
        <script type="text/javascript" src="{{ url('web/js/select-ar.js') }}"></script>
        <script type="text/javascript" src="{{ url('web/js/messages_ar.min.js') }}"></script>
    @endif

    <!--for this page only-->
    <script type="text/javascript" src="{{ asset('web/js/anime.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('web/js/custom-pages.js') }}"></script>
    <script type="text/javascript" src="{{ asset('web/js/donate.js') }}"></script>

    <!-- validation laravel -->
    <script src="{{ url('custom/custom-validate.js') }}"></script>   

@endpush

resources/views/web/donates/get_project_ofcategory.blade.php
    <select class="form-control select-input project_id" data-action="{{ route('web.check.project') }}" name="projects" id="check_project" required>
        <option selected disabled></option>
        @foreach($projects as $project)
            <option value="{{ $project->id }}">{{ $project->name }} - {{ $project->project_num }}</option>
        @endforeach
    </select>
    <label class="moving-label">{{ __('web.project_name') }}</label>

resources/views/web/donates/header.blade.php
    <!-- start pages-header
         ================ -->
         <section class="pages-header text-center" style="background-image:url({{ asset('storage/'.$pages_header) }})">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="pages-header-content line-title">
                        <span class="line"></span>
                        <h1 class="white-text bold-text text-upper">{{ __('web.donate_now') }}</h1>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--end pages-header-->